### ISSUE TITLE
FRONTEND CHECKLIST WINTER HOLIDAYS

### ISSUE THREAD

**Issue by BEATM-P** [omah03/Usable-Machine-Learning-#38]
- [ ] change Tabs layout
- [x] improve infobox
- [x] structure cleanup
- [ ] connect train to backend
- [x] connect param to backend
- [ ] rework output linear layer and classification
      - make it scalable
      - make it more intuitive/better idk 
- [ ] make it sexy
